### ISSUE TITLE
GamePod XL 

### ISSUE THREAD

**Issue by tnmendes** [bbbbbr/Petris#1]
Hi bbbbbr,

I'm Tiago I'm an iOS Developer and in the last few weeks in my spare time, I've been doing something like a "game console" for the iPhone. What I mean by "game console" is basically using the AirPlay functionality which allows Multi-screen Support to run various HTML games, GB and Pico-8 from multiple developers on the TV and use the iPhone as a gamepad.
I tried your game Petris and I really liked it, so I would like to ask permission to have your game running in my app.
The app is free for everyone and the games also gonna be free. When someone selects your game, a brief description of the game will show and your name (bbbbbr) will appear.

The app is already available, with some games. The name of the app is "GamePod XL for Airplay".

Do you authorize me to have your game Petris available in my app!?

Thank you and sorry for the inconvenience,
Tiago Mendes

**Comment by bbbbbr** [comment]
Hello,

Thank you for inquiring, I'm glad you like the program. You may include Petris in your project as long as it meets the following conditions (set out in LICENSE in this repo). Additional comments in parenthesis.

* Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses
you or your use.
  * _(You've already mentioned username attribution which is great. Ideally it would also include a clickable web link to this github repository or the itch.io page for Petris, https://bbbbbr.itch.io/petris)_

* NonCommercial — You may not use the material for commercial purposes. 
  * _(Your program must be zero cost, as you already mentioned. If your project changes to charge money or the project is sold then the ability to include Petris will need to be re-agreed upon. If you make money from advertising, that is ok.)_

* ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
  * _(For this request, this only applies to the game itself and not the project you are building. If you modify Petris then it applies)_

* No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.


I hope your project goes well!

**Comment by tnmendes** [comment]
Hi bbbbbr,

Thank you for your response and for granting permission to include Petris in the project. I understand and agree to the conditions you have set out in your message, including providing appropriate attribution, ensuring the app is non-commercial, and abiding by the terms of the license.

I currently don't have adequate space to include a clickable web link to your Github repository or itch.io page.
I will try in the next version to add more buttons to be able to handle clickable web links and show the URL for the license.

Once again, thank you for your permission, and I look forward to including your game in my app :D 

Best regards,
Tiago Mendes
